const StringConstants = {
  BASIC: "BASIC",
  BASIC_CLASSIFIER: "The basic image classifier model is Google's Vision Transformer from Hugging Face, pre-trained on ImageNet",
  CLASSIFY: "Classify",
  CREATE_ACCOUNT: "Create account",
  CURRENTLY_TRAINING: "Your model is being trained...",
  CUSTOM: "CUSTOM",
  DELETE: "Delete",
  EMAIL_VERIFICATION_REQUIRED: "Email verification required",
  HOME: "Home",
  LOGIN: "Login",
  LOGOUT: "Logout",
  MODEL_SELECTION: "Select a model:",
  MY_ACCOUNT: "My Account",
  ONE_MODEL: "To save resources, users are only allowed one customizable image classification model",
  RESEND_VERIFICATION_EMAIL: "Resend Verification Email",
  START_TRAINING: "Start training",
  UPLOAD_AND_TRAIN: "UPLOAD & TRAIN",
  UNEXPECTED_ERROR: "Unexpected error occurred.",
  TRAIN: "TRAIN",
  TRAINING_TIME: "For a training set of 100 images, expect around 5 minutes of training time.",
  VERIFICATION_CODE: "Please enter the 6-digit verification code sent to your email",
  VERIFY: "Verify",
};

export default StringConstants;
